### ISSUE TITLE
java.lang.NoClassDefFoundError: atownsend.swipeopenhelper.SwipeOpenItemTouchHelper$SimpleCallback

### ISSUE THREAD

**Issue by z244370114** [alex-townsend/SwipeOpenItemTouchHelper#14]
java.lang.NoClassDefFoundError:atownsend.swipeopenhelper.SwipeOpenItemTouchHelper$SimpleCallback
why

**Comment by alex-townsend** [comment]
Have you properly imported the library through gradle?

**Comment by z244370114** [comment]
BuildToolsVersion 23.0.3 ""
I changed this version, the other didn't change.

**Comment by lsqboy** [comment]
FATAL EXCEPTION: main
                                                                         Process: atownsend.swipeopenhelper, PID: 7995
                                                                         java.lang.NoClassDefFoundError: atownsend.swipeopenhelper.SwipeOpenItemTouchHelper$SimpleCallback
                                                                             at atownsend.sample.MainActivity.onCreate(MainActivity.java:31)
                                                                             at android.app.Activity.performCreate(Activity.java:5280)
                                                                             at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1087)
                                                                             at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2239)
                                                                             at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2325)
                                                                             at android.app.ActivityThread.access$1100(ActivityThread.java:141)
                                                                             at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1238)
                                                                             at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                             at android.os.Looper.loop(Looper.java:136)
                                                                             at android.app.ActivityThread.main(ActivityThread.java:5291)
                                                                             at java.lang.reflect.Method.invokeNative(Native Method)
                                                                             at java.lang.reflect.Method.invoke(Method.java:515)
                                                                             at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:865)
                                                                             at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:681)
                                                                             at dalvik.system.NativeStart.main(Native Method)

**Comment by alex-townsend** [comment]
@Lsqboy when is this error occurring? Are you trying to build the sample project and having it fail?

**Comment by z244370114** [comment]
I have built a new project, and I have made the mistake.

**Comment by ar-g** [comment]
also have crashed, I found that it crashed because of and only Android 4.2

E/dalvikvm: Method Latownsend/sample/Callback;.getAbsoluteMovementFlags overrides final Landroid/support/v7/widget/helper/ItemTouchHelper$Callback;.getAbsoluteMovementFlags

After renaming this method seems to work

**Comment by alex-townsend** [comment]
@ar-g nice catch -- I think that's what's causing the other issues as well. I'll have a fix in for the dalvik crash later today.

**Comment by alex-townsend** [comment]
Just merged in a fix with #17. Pointing to a snapshot build should fix the issue immediately. I'll do a new release soon once I've got a couple other enhancements put in.

**Comment by alex-townsend** [comment]
Closing this as the fix was added.
