### ISSUE TITLE
NullPointerException

### ISSUE THREAD

**Issue by oxcened** [alex-townsend/SwipeOpenItemTouchHelper#37]
Am i missing something?

```
`03-11 12:23:55.988 6242-6242/com.company.app E/AndroidRuntime: FATAL EXCEPTION: main
                                                                  Process: com.company.app, PID: 6242
                                                                  java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.Object android.view.View.getTag(int)' on a null object reference
                                                                      at android.support.v7.widget.helper.ItemTouchUIUtilImpl$Lollipop.clearView(ItemTouchUIUtilImpl.java:65)
                                                                      at atownsend.swipeopenhelper.SwipeOpenItemTouchHelper$Callback.clearView(SwipeOpenItemTouchHelper.java:1266)
                                                                      at atownsend.swipeopenhelper.SwipeOpenItemTouchHelper.onChildViewDetachedFromWindow(SwipeOpenItemTouchHelper.java:740)
                                                                      at android.support.v7.widget.RecyclerView.dispatchChildDetached(RecyclerView.java:6780)
                                                                      at android.support.v7.widget.RecyclerView$5.removeViewAt(RecyclerView.java:718)
                                                                      at android.support.v7.widget.ChildHelper.removeViewAt(ChildHelper.java:168)
                                                                      at android.support.v7.widget.RecyclerView$LayoutManager.removeViewAt(RecyclerView.java:7766)
                                                                      at android.support.v7.widget.RecyclerView$LayoutManager.scrapOrRecycleView(RecyclerView.java:8312)
                                                                      at android.support.v7.widget.RecyclerView$LayoutManager.detachAndScrapAttachedViews(RecyclerView.java:8298)
                                                                      at android.support.v7.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:561)
                                                                      at android.support.v7.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:3537)
                                                                      at android.support.v7.widget.RecyclerView.dispatchLayout(RecyclerView.java:3266)
                                                                      at android.support.v7.widget.RecyclerView.onLayout(RecyclerView.java:3798)
                                                                      at android.view.View.layout(View.java:17637)
                                                                      at android.view.ViewGroup.layout(ViewGroup.java:5575)
                                                                      at android.support.design.widget.CoordinatorLayout.layoutChild(CoordinatorLayout.java:1167)
                                                                      at android.support.design.widget.CoordinatorLayout.onLayoutChild(CoordinatorLayout.java:852)
                                                                      at android.support.design.widget.ViewOffsetBehavior.layoutChild(ViewOffsetBehavior.java:63)
                                                                      at android.support.design.widget.HeaderScrollingViewBehavior.layoutChild(HeaderScrollingViewBehavior.java:135)
                                                                      at android.support.design.widget.ViewOffsetBehavior.onLayoutChild(ViewOffsetBehavior.java:42)
                                                                      at android.support.design.widget.AppBarLayout$ScrollingViewBehavior.onLayoutChild(AppBarLayout.java:1375)
                                                                      at android.support.design.widget.CoordinatorLayout.onLayout(CoordinatorLayout.java:870)
                                                                      at android.view.View.layout(View.java:17637)
                                                                      at android.view.ViewGroup.layout(ViewGroup.java:5575)
                                                                      at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
                                                                      at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
                                                                      at android.view.View.layout(View.java:17637)
                                                                      at android.view.ViewGroup.layout(ViewGroup.java:5575)
                                                                      at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
                                                                      at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
                                                                      at android.view.View.layout(View.java:17637)
                                                                      at android.view.ViewGroup.layout(ViewGroup.java:5575)
                                                                      at android.support.design.widget.CoordinatorLayout.layoutChild(CoordinatorLayout.java:1167)
                                                                      at android.support.design.widget.CoordinatorLayout.onLayoutChild(CoordinatorLayout.java:852)
                                                                      at android.support.design.widget.CoordinatorLayout.onLayout(CoordinatorLayout.java:871)
                                                                      at android.view.View.layout(View.java:17637)
                                                                      at android.view.ViewGroup.layout(ViewGroup.java:5575)
                                                                      at android.support.v4.widget.DrawerLayout.onLayout(DrawerLayout.java:1193)
                                                                      at android.view.View.layout(View.java:17637)
                                                                      at android.view.ViewGroup.layout(ViewGroup.java:5575)
                                                                      at android.support.v4.widget.DrawerLayout.onLayout(DrawerLayout.java:1193)
                                                                      at android.view.View.layout(View.java:17637)
                                                                      at android.view.ViewGroup.layout(ViewGroup.java:5575)
                                                                      at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
                                                                      at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
                                                                      at android.view.View.layout(View.java:17637)
                                                                      at android.view.ViewGroup.layout(ViewGroup.java:5575)
                                                                      at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1741)
                                                                      at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1585)
                                                                      at android.widget.LinearLayout.onLayout(LinearLayout.java:1494)
                                                                      at android.view.View.layout(View.java:17637)
03-11 12:23:55.989 6242-6242/com.company.app E/AndroidRuntime:     at android.view.ViewGroup.layout(ViewGroup.java:5575)
                                                                      at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
                                                                      at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
                                                                      at android.view.View.layout(View.java:17637)
                                                                      at android.view.ViewGroup.layout(ViewGroup.java:5575)
                                                                      at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1741)
                                                                      at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1585)
                                                                      at android.widget.LinearLayout.onLayout(LinearLayout.java:1494)
                                                                      at android.view.View.layout(View.java:17637)
                                                                      at android.view.ViewGroup.layout(ViewGroup.java:5575)
                                                                      at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
                                                                      at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
                                                                      at com.android.internal.policy.DecorView.onLayout(DecorView.java:726)
                                                                      at android.view.View.layout(View.java:17637)
                                                                      at android.view.ViewGroup.layout(ViewGroup.java:5575)
                                                                      at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:2346)
                                                                      at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2068)
                                                                      at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1254)
                                                                      at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6337)
                                                                      at android.view.Choreographer$CallbackRecord.run(Choreographer.java:874)
                                                                      at android.view.Choreographer.doCallbacks(Choreographer.java:686)
                                                                      at android.view.Choreographer.doFrame(Choreographer.java:621)
                                                                      at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:860)
                                                                      at android.os.Handler.handleCallback(Handler.java:751)
                                                                      at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                      at android.os.Looper.loop(Looper.java:154)
                                                                      at android.app.ActivityThread.main(ActivityThread.java:6119)
                                                                      at java.lang.reflect.Method.invoke(Native Method)
                                                                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
                                                                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)
```

Adapter:
```
`public class RecyclerAdapterMain extends RecyclerView.Adapter<RecyclerAdapterMain.RecyclerViewHolder>{
    private ArrayList<String> title;
    private int mExpandedPosition = -1;
    private RecyclerView recyclerView;

    public RecyclerAdapterMain(ArrayList<String> title){
        this.title = title;
    }
    @Override
    public RecyclerViewHolder onCreateViewHolder(ViewGroup parent, int viewType) {
        View view = LayoutInflater.from(parent.getContext()).inflate(R.layout.card_view,parent,false);
        return new RecyclerViewHolder(view);
    }

    @Override
    public void onBindViewHolder(final RecyclerViewHolder holder, final int position) {
        holder.titleTextView.setText(title.get(position));
        holder.buttonView.setText(holder.context.getString(R.string.show));
        holder.buttonView.setGravity(Gravity.LEFT | Gravity.CENTER_VERTICAL);
        holder.helpButton.setVisibility(View.GONE);
        holder.buttonView.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View view) {
                if(!holder.settings.getBoolean("BUTTONS_RV_CONFIG_DISABLED",false)){
                    view.getContext().startActivity(new Intent(view.getContext(),ConfigurationSavedActivity.class).putExtra("EXTRA_SAVED",position)); //NON-NLS
                }
            }
        });
        holder.subtitleTextView.setText(holder.context.getString(R.string.configuration));

        final boolean isExpanded = position==mExpandedPosition;
        holder.buttonView.setVisibility(isExpanded?View.VISIBLE:View.GONE);
        holder.itemView.setActivated(isExpanded);
        holder.itemView.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View v) {
                mExpandedPosition = isExpanded ? -1:position;
                TransitionManager.beginDelayedTransition(recyclerView);
                notifyDataSetChanged();
            }
        });
    }

    @Override
    public void onAttachedToRecyclerView(RecyclerView recyclerView) {
        super.onAttachedToRecyclerView(recyclerView);

        this.recyclerView = recyclerView;
    }

    @Override
    public int getItemCount() {
        return title.size();
    }

    public static class RecyclerViewHolder extends BaseSwipeOpenViewHolder{
        private TextView titleTextView, subtitleTextView;
        private Button buttonView;
        private ImageView helpButton;
        private Context context = itemView.getContext();
        private CardView cardView;
        private SharedPreferences settings;
        private final String PREFS_NAME = "MyPrefsFile"; //NON-NLS



        public LinearLayout contentView;
        public TextView textView;
        public TextView deleteButton;
        public TextView editButton;



        public RecyclerViewHolder(View itemView) {
            super(itemView);
            titleTextView = (TextView) itemView.findViewById(R.id.title);
            buttonView = (Button) itemView.findViewById(R.id.button);
            helpButton = (ImageView) itemView.findViewById(R.id.img_help);
            subtitleTextView = (TextView) itemView.findViewById(R.id.subtitle);
            cardView = (CardView) itemView.findViewById(R.id.card_view);
            settings = context.getSharedPreferences(PREFS_NAME, MODE_PRIVATE);


            contentView = (LinearLayout) itemView.findViewById(R.id.content_view);
            textView = (TextView) itemView.findViewById(R.id.display_text);
            deleteButton = (TextView) itemView.findViewById(R.id.delete_button);
            editButton = (TextView) itemView.findViewById(R.id.edit_button);
        }

        @NonNull
        @Override
        public View getSwipeView() {
            return contentView;
        }

        @Override
        public float getEndHiddenViewSize() {
            return editButton.getMeasuredHeight();
        }

        @Override
        public float getStartHiddenViewSize() {
            return deleteButton.getMeasuredHeight();
        }
    }
}`
```

Fragment:

```
`recyclerView = (RecyclerView) rootView.findViewById(R.id.recyclerViewMain);
        adapter = new RecyclerAdapterMain(title);
        layoutManager = new LinearLayoutManager(getContext());
        recyclerView.setLayoutManager(layoutManager);
        recyclerView.setHasFixedSize(true);
        recyclerView.setAdapter(adapter);
       SwipeOpenItemTouchHelper help = new SwipeOpenItemTouchHelper(new               SwipeOpenItemTouchHelper.SimpleCallback(SwipeOpenItemTouchHelper.START | SwipeOpenItemTouchHelper.END));
        help.attachToRecyclerView(recyclerView);
        help.setCloseOnAction(false);
`
```

**Comment by alex-townsend** [comment]
Looking at the stack trace, the view returning for _getSwipeView()_ is null.

**Comment by oxcened** [comment]
My bad i've messed up with the layout, thanks by the way.

**Comment by oxcened** [comment]
Everything is working fine now, thank you for developing this!
