### ISSUE TITLE
ANR swipe

### ISSUE THREAD

**Issue by pavel163** [alex-townsend/SwipeOpenItemTouchHelper#41]
Hi! I start to use your library with support library 26.1.0 and I have ANR: When do I swipe
```
java.lang.NoClassDefFoundError: Failed resolution of: Landroid/support/v4/animation/AnimatorListenerCompat;
                                                                              Caused by: java.lang.ClassNotFoundException: Didn't find class "android.support.v4.animation.AnimatorListenerCompat" on path: DexPathList[[zip file "/data/app/ru.psbank.msb.dev.psb_dev_test-2/base.apk"],nativeLibraryDirectories=[/data/app/ru.psbank.msb.dev.psb_dev_test-2/lib/arm64, /system/lib64, /vendor/lib64]]
                                                                                  at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
                                                                                  at java.lang.ClassLoader.loadClass(ClassLoader.java:380)
                                                                                  at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
```

**Comment by alex-townsend** [comment]
Are you using version 1.4.0 of the library?

**Comment by pavel163** [comment]
@alex-townsend No. Now I use 1.4.0, but I have this issue 
```
Error:Execution failed for task ':app:transformClassesWithJarMergingForPsb_dev_testRelease'.
> com.android.build.api.transform.TransformException: java.util.zip.ZipException: duplicate entry: atownsend/swipeopenhelper/SwipeOpenItemTouchHelper$RecoverAnimation.class
```

**Comment by alex-townsend** [comment]
Sounds like a problem with your gradle setup causing the library to be included twice.

**Comment by pavel163** [comment]
version 1.4.0 work! Update readme please.
